apiVersion: v1
kind: Namespace
metadata:
  name: metabase
  labels:
    name: metabase
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: metabase
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-pvc
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        env:
          - name: MB_PROMETHEUS_SERVER_PORT
            value: "9191"
        envFrom:
          - secretRef:
              name: tf-datasquad-eks-metabase-db-secret
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: metabase-data
          mountPath: /metabase-data
      volumes:
      - name: metabase-data
        persistentVolumeClaim:
          claimName: metabase-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: metabase-ingress
  namespace: metabase
spec:
  ingressClassName: nginx
  rules:
  - host: metabase.prod.datalake.garageeducation.org
    http:
      paths:
        - backend:
            service:
              name: metabase
              port:
                number: 3000
          path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - metabase.prod.datalake.garageeducation.org
    secretName: letsencrypt-production
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metabase
  namespace: metabase
  labels:
    app: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  endpoints:
    - path: /metrics
      targetPort: 9191
      interval: 30s