apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: tf-datasquad-eks-metabase-sa
  namespace: metabase
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::730335474513:role/tf-datasquad-eks-metabase-app-irsa"
  labels:
    app.kubernetes.io/instance: tf-datasquad-eks-metabase-sa
    app.kubernetes.io/name: tf-datasquad-eks-metabase-sa