apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tf-datasquad-eks-metabase-db-store
  namespace: metabase
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: tf-datasquad-eks-metabase-sa