apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-datasquad-rds-db-secret
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tf-datasquad-rds-db-store
    kind: SecretStore
  target:
    name: tf-datasquad-rds-db-secret
    creationPolicy: Owner
  data:
  - secretKey: PGUSER
    remoteRef:
      key: "rds!db-390eb28a-2563-4d84-b9f1-9b3205f59365"
      property: username
  - secretKey: PGPASSWORD
    remoteRef:
      key: "rds!db-390eb28a-2563-4d84-b9f1-9b3205f59365"
      property: password
  - secretKey: PGPORT
    remoteRef:
      key: "tf-petclinic-db-secret"
      property: POSTGRES_PORT
  - secretKey: PGDATABASE
    remoteRef:
      key: "tf-petclinic-db-secret"
      property: POSTGRES_DB
  - secretKey: PGHOST
    remoteRef:
      key: "tf-petclinic-db-secret"
      property: POSTGRES_HOST