apiVersion: v1
kind: Namespace
metadata:
  name: petclinic
  labels:
    name: petclinic
---
# Create the database service
apiVersion: v1
kind: Service
metadata:
  name: rds-app-db
  namespace: db
spec:
 type: ExternalName
 externalName: tf-datasquad-app-db.cds82uaqe36x.eu-west-1.rds.amazonaws.com