apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
  namespace: petclinic-production
spec:
  externalName: tf-datasquad-petclinic-db.ourcpo0qnztu.eu-west-1.rds.amazonaws.com
  sessionAffinity: None
  type: ExternalName
