apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/name: petclinic
  name: petclinic-service
  namespace: petclinic
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: petclinic
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/name: petclinic
  type: ClusterIP