apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-datasquad-eks-petclinic-db-secret
  namespace: petclinic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tf-datasquad-eks-petclinic-db-store
    kind: SecretStore
  target:
    name: tf-datasquad-eks-petclinic-db-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: tf-petclinic-db-secret
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASS
    remoteRef:
      key: tf-petclinic-db-secret
      property: POSTGRES_PASS
  - secretKey: POSTGRES_URL
    remoteRef:
      key: tf-petclinic-db-secret
      property: POSTGRES_URL