#https://www.kloia.com/blog/kubernetes-secret-management-using-the-external-secrets-operator-eks
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tf-datasquad-eks-petclinic-db-store
  namespace: petclinic
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: petclinic-app-external-secret-sa