apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: petclinic-app-external-secret-sa
  namespace: petclinic
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::730335474513:role/tf-datasquad-eks-petclinic-app-irsa"
  labels:
    app.kubernetes.io/instance: petclinic-app-external-secret-sa
    app.kubernetes.io/name: petclinic-app-external-secret-sa